### ISSUE TITLE
install.sh问题

### ISSUE THREAD

**Issue by 0xAyin** [yuesong-feng/EasyVim#3]
- 地址访问出错

$ sh ./install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
Finish install EasyVim!!!
start vim and run :PlugInstall

**Comment by yuesong-feng** [comment]
没挂VPN，国内无法访问GitHub

**Comment by 0xAyin** [comment]
ok
